### ISSUE TITLE
[BUG] - Age incorrect, does not account for month

### ISSUE THREAD

**Issue by flennic** [personnummer/csharp#103]
**Context**

It seems that the calculation of the age is wrong. Given that "today" is defined as 04.11.2024 and that the personal number is "19841120-0788":

**Expected outcome**

The age should be 39, as the person did not have birthday yet (20. November).

**Actual outcome**

40.

**Description**

The calculation only takes into account the years (2024 - 1984) but does not account for the month. I am not sure this is maybe the "age" definition according to some law or personal number requirement. But if not, it is most likely a bug.

If you confirm that it is a bug, I can create a PR fixing the issue.

**Minimal reproducible test case**

Set system time to 04.10.2024, any time.

```csharp
var personnummer = new Personnummer.Personnummer("19841120-0788");  
Console.WriteLine(personnummer.Age);
```

**Comment by flennic** [comment]
PR created here: https://github.com/personnummer/csharp/pull/104

**Comment by Johannestegner** [comment]
Quite amazed that we haven't seen this before, quite a novice mistake on how _I_ implemented the age check. 
Thanks for the find! :)
