### ISSUE TITLE
[BUG] -

### ISSUE THREAD

**Issue by MagnusAycox** [personnummer/csharp#31]
**Context**

This was found in version 3.0.2 of the component.
The OS where found is Windows 10 Professional 64 bit.
As the bug was found in the main code path, it affects all environments (debug, production etc).

**Expected outcome**

The `IsCoordinationNumber` property should properly indicate if the current ssn is a "samordningsnummer"/coordination number.

**Actual outcome**

The `IsCoordinationNumber` property is always true when coordination numbers are enabled/allowed.

**Description**

The code always sets the `IsCoordinationNumber` to true when coordination numbers are allowed.
This is due to the below code.
```
if (options.Value.AllowCoordinationNumber)
{
  num1 = num1 > 60 ? num1 - 60 : num1;
  this.IsCoordinationNumber = true;
}
```
It should instead be:
```
if (options.Value.AllowCoordinationNumber)
{
  this.IsCoordinationNumber = num1 > 60;
  num1 = num1 > 60 ? num1 - 60 : num1;
}
```

**Minimal reproducible test case**

```
var ssn = new Personnummer.Personnummer("700102-5316");
Assert.IsFalse(ssn.IsCoordinationNumber);
```

**Comment by Johannestegner** [comment]
Thank you for the report, will fix asap!
