### ISSUE TITLE
Incorrect validation

### ISSUE THREAD

**Issue by lundopendata** [personnummer/csharp#5]
This is a valid personnummer but the unittest fails :-/

```
[InlineData("550207-3900", true)]
 public void TestPersonnummerString(string value, bool expected)
        {
            Assert.Equal(Personnummer.Valid(value), expected);
        }
```

**Comment by Johannestegner** [comment]
Thanks for the report and pull request, I will take a look at it as soon as possible!

**Comment by Johannestegner** [comment]
PR can be found at #6

**Comment by Johannestegner** [comment]
As soon as I have time (have had a very very busy schedule) I'll take a look at this issue.

The earlier PR have not been fixed after review comments, so if someone intends to do a fix before I have time, create a new PR,. :)
